/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWikiRouteImport } from './routes/_authenticated/wiki'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedIdRouteImport } from './routes/_authenticated/$id'
import { Route as AuthenticatedWikiIndexRouteImport } from './routes/_authenticated/wiki.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients/new'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients/$clientId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWikiRoute = AuthenticatedWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIdRoute = AuthenticatedIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWikiIndexRoute = AuthenticatedWikiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedWikiRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/$id': typeof AuthenticatedIdRoute
  '/new': typeof AuthenticatedNewRoute
  '/team': typeof AuthenticatedTeamRoute
  '/wiki': typeof AuthenticatedWikiRouteWithChildren
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/wiki/': typeof AuthenticatedWikiIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$id': typeof AuthenticatedIdRoute
  '/new': typeof AuthenticatedNewRoute
  '/team': typeof AuthenticatedTeamRoute
  '/': typeof AuthenticatedIndexRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/wiki': typeof AuthenticatedWikiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/$id': typeof AuthenticatedIdRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/wiki': typeof AuthenticatedWikiRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/wiki/': typeof AuthenticatedWikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$id'
    | '/new'
    | '/team'
    | '/wiki'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients/'
    | '/wiki/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$id'
    | '/new'
    | '/team'
    | '/'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients'
    | '/wiki'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/$id'
    | '/_authenticated/new'
    | '/_authenticated/team'
    | '/_authenticated/wiki'
    | '/_authenticated/'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/clients/new'
    | '/_authenticated/clients/'
    | '/_authenticated/wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wiki': {
      id: '/_authenticated/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof AuthenticatedWikiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$id': {
      id: '/_authenticated/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof AuthenticatedIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wiki/': {
      id: '/_authenticated/wiki/'
      path: '/'
      fullPath: '/wiki/'
      preLoaderRoute: typeof AuthenticatedWikiIndexRouteImport
      parentRoute: typeof AuthenticatedWikiRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedWikiRouteChildren {
  AuthenticatedWikiIndexRoute: typeof AuthenticatedWikiIndexRoute
}

const AuthenticatedWikiRouteChildren: AuthenticatedWikiRouteChildren = {
  AuthenticatedWikiIndexRoute: AuthenticatedWikiIndexRoute,
}

const AuthenticatedWikiRouteWithChildren =
  AuthenticatedWikiRoute._addFileChildren(AuthenticatedWikiRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedIdRoute: typeof AuthenticatedIdRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedWikiRoute: typeof AuthenticatedWikiRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIdRoute: AuthenticatedIdRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedWikiRoute: AuthenticatedWikiRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
